[camera]
pos = [50.0, 52.0, 295.6]
dir = [0.0, -0.042612, -1.0]

# Left wall
[[objects]]
brdf = { type = "diffuse", kd = [0.75, 0.25, 0.25] }
geometry = { type = "plane", pos = [1.0, 0.0, 0.0], n = [-1.0, 0.0, 0.0] }

# Right wall
[[objects]]
brdf = { type = "diffuse", kd = [0.25, 0.25, 0.75] }
geometry = { type = "plane", pos = [99.0, 0.0, 0.0], n = [-1.0, 0.0, 0.0] }

# Back wall
[[objects]]
brdf = { type = "diffuse", kd = [0.75, 0.75, 0.75] }
geometry = { type = "plane", pos = [0.0, 0.0, 0.0], n = [0.0, 0.0, -1.0] }

# Floor
[[objects]]
brdf = { type = "diffuse", kd = [0.75, 0.75, 0.75] }
geometry = { type = "plane", pos = [0.0, 0.0, 0.0], n = [0.0, 1.0, 0.0] }

# Ceiling
[[objects]]
brdf = { type = "diffuse", kd = [0.75, 0.75, 0.75] }
geometry = { type = "plane", pos = [0.0, 81.6, 0.0], n = [0.0, -1.0, 0.0] }

# Wall behind camera
[[objects]]
brdf = { type = "diffuse", kd = [0.75, 0.75, 0.75] }
geometry = { type = "plane", pos = [99.0, 0.0, 0.0], n = [-1.0, 0.0, 0.0] }

# Unicorn
[[objects]]
brdf = { type = "diffuse", kd = [0.9, 0.9, 0.9] }
geometry = { type = "mesh", path = "flying-unicorn.obj" }
transforms = [
    { scale = 5.0 },
    { translate = [35.0, 25.0, 65.0] },
    { rotate_z = -0.4 },
    { rotate_x = -1.5707963267948966 },
]

# Ball
[[objects]]
brdf = { type = "specular", ks = [0.999, 0.999, 0.999] }
geometry = { type = "sphere", pos = [73.0, 16.5, 68.0], r = 16.5 }

# Light
[[objects]]
emitted = [50.0, 50.0, 50.0]
brdf = { type = "diffuse", kd = [0.0, 0.0, 0.0] }
geometry = { type = "sphere", pos = [50.0, 70.0, 100.0], r = 4.0 }
